version: '3.8'

services:
  plant_tracker_node:
    container_name: plant_tracker_node
    image: node:lts
    volumes:
      - ../:/app
    restart: always
    tty: true
    stdin_open: true
    working_dir: /app
    ports:
      - "3000:3000"
